version: '3'
services:
  my-app:
    image: maymc/knex-shopping:${IMAGE_VERSION}-local
    depends_on:
      - db
    command: ['npm', 'run', 'dev']
    container_name: knex-shopping
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
      - "3000:3000"
      - "3001:3001"
    networks:
      - my-app-network
  db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network
volumes:
  pg-data-volume:
networks:
  my-app-network: